### ISSUE TITLE
Not launching on Ubuntu 22.04 

### ISSUE THREAD

**Issue by mendhak** [patrick330602/electron-microsoft-todo#3]
Hi I've installed this snap, but when trying to launch it nothing happens.  
I've tried both the application icon, and the CLI as well, but there's no output and the app never appears. 

I tried

    $ snap run microsoft-todo-unofficial

but not output.  I'm not familiar enough with snaps to know where to look or how to see any logs?

```
$ snap version
snap    2.56.2+22.04ubuntu1
snapd   2.56.2+22.04ubuntu1
series  16
ubuntu  22.04
kernel  5.15.0-47-generic
```

**Comment by maximilianpalm** [comment]
I've been having the same issue for a while now on Ubuntu 22.04.1 LTS. Neither GNOME icon nor CLI yield any kind of reaction. 

Here is what I've tried so far:
```
$ sudo snap remove --purge microsoft-todo-unofficial
microsoft-todo-unofficial removed
$ sudo snap install microsoft-todo-unofficial
microsoft-todo-unofficial 1.2.3 from Patrick Wu (patrick330602) installed
$ microsoft-todo-unofficial
$ microsoft-todo-unofficial --help
$ microsoft-todo-unofficial --debug
$ microsoft-todo-unofficial -v
$ microsoft-todo-unofficial -?
$ microsoft-todo-unofficial asdf
$ microsoft-todo-unofficial -asdf
$ microsoft-todo-unofficial --asdf
$ snap run microsoft-todo-unofficial
$ ps -ef | grep todo
user       17848    3661  0 09:00 ?        00:00:00 /usr/bin/gnome-todo --gapplication-service
user       22923   17677  0 09:10 pts/0    00:00:00 grep --color=auto todo
```

Version info
```
$ sudo snap list | grep  microsoft-todo-unofficial
microsoft-todo-unofficial             1.2.3                       4      latest/stable    patrick330602   -

$ snap --version
snap    2.57.6
snapd   2.57.6
series  16
ubuntu  22.04
kernel  5.15.0-56-generic

$ uname -a
Linux box 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by maximilianpalm** [comment]
Update: As a workaround, I tried installing directly from git. I got some error messages **but the app started**:

```
$ sudo apt-get install npm
[...]
0 upgraded, 188 newly installed, 0 to remove and 18 not upgraded.
[...]
```
```
$ git clone https://github.com/patrick330602/electron-microsoft-todo.git
Cloning into 'electron-microsoft-todo'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 107 (delta 3), reused 9 (delta 3), pack-reused 97
Receiving objects: 100% (107/107), 189.81 KiB | 4.41 MiB/s, done.
Resolving deltas: 100% (45/45), done.
```
```
$ cd electron-microsoft-todo/
```
```
$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'app-builder-lib@22.13.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'electron-builder@22.13.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

> microsoft-todo-unofficial@1.2.3 postinstall
> electron-builder install-app-deps

Error: Cannot find module 'fs/promises'
Require stack:
- /mnt/data/Downloads/electron-microsoft-todo/node_modules/builder-util/out/fs.js
- /mnt/data/Downloads/electron-microsoft-todo/node_modules/builder-util/out/util.js
- /mnt/data/Downloads/electron-microsoft-todo/node_modules/electron-builder/out/cli/cli.js
- /mnt/data/Downloads/electron-microsoft-todo/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/data/Downloads/electron-microsoft-todo/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/data/Downloads/electron-microsoft-todo/node_modules/builder-util/src/util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code 1
npm ERR! path /mnt/data/Downloads/electron-microsoft-todo
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-12-10T08_32_23_194Z-debug-0.log
```
```
$ npm start

> microsoft-todo-unofficial@1.2.3 start
> electron .

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[27744:1210/093234.755360:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```
After this, the app window opened and I was able to login and see my todos.

**Comment by patrick330602** [comment]
I am currently working on this

**Comment by patrick330602** [comment]
it should now work
